apiVersion: v1
kind: Service
metadata:
  name: {{.Values.app.name }}-service
  namespace: default
spec:
  type: NodePort
  ports:
    - port: {{.Values.app.service.port }}
      targetPort: {{.Values.app.service.port }}
  selector:
    app: {{.Values.app.name }}
